name: Deploy shiny app

on:
  workflow_dispatch:
    inputs:
      target_scale_set:
        description: "Which scale set to deploy?"
        type: string
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: nand42/test-onyxia
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app/
          file: ./app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            ${{ github.ref == 'refs/heads/main' && 'nand42/test-onyxia:latest' || '' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.1'
        id: install_kubectl
      - uses: azure/setup-helm@v4.2.0
        with:
          version: '3.14.4'
        id: install_helm

      - name: Set credentials
        run : |
          kubectl config set-cluster apiserver.kub.sspcloud.fr \
          --server=https://apiserver.kub.sspcloud.fr \
          --insecure-skip-tls-verify=true

          kubectl config set-credentials ${{ secrets.ONYXIA_USERNAME }} \
            --auth-provider=oidc  \
            --auth-provider-arg=idp-issuer-url=https://auth.lab.sspcloud.fr/auth/realms/sspcloud  \
            --auth-provider-arg=client-id=onyxia  \
            --auth-provider-arg=refresh-token=${{ secrets.ONYXIA_REFRESH_TOKEN }}  \
            --auth-provider-arg=id-token=${{ secrets.ONYXIA_ID_TOKEN }}

          kubectl config set-context apiserver.kub.sspcloud.fr \
            --user=${{ secrets.ONYXIA_USERNAME }} \
            --cluster=apiserver.kub.sspcloud.fr \
            --namespace=user-${{ secrets.ONYXIA_USERNAME }}

          kubectl config use-context apiserver.kub.sspcloud.fr
      - name: "Deploy helm charts"
        run : |
          helm dependency update ./charts
          helm upgrade ananda ./charts  --recreate-pods --install 
